import dotenv from 'dotenv'; import { chromium } from '@playwright/test';
dotenv.config({path:'.env.prod'}); dotenv.config({path:'.env.prod.secrets'});
const WEB=process.env.KEFI_WEB_URL;
const b=await chromium.launch(); const ctx=await b.newContext(); const p=await ctx.newPage();
p.on('pageerror', e=>console.log('PAGEERROR:', e.message));
p.on('console', m=>{ if(m.type()==='error') console.log('CONSOLE-ERR:', m.text().slice(0,200)); });
p.on('response', async r=>{ const u=r.url(); if(/bff|login|token|organizer|access-link/.test(u) && r.status()>=400) console.log('HTTP', r.status(), r.request().method(), u.slice(0,140)); });
await p.goto(`${WEB}/login`);
await p.getByTestId('kefi-login-username').fill(process.env.KEFI_FIXTURE_ORGANIZER_USERNAME);
await p.getByTestId('kefi-login-password').fill(process.env.KEFI_FIXTURE_ORGANIZER_PASSWORD);
await p.getByTestId('kefi-login-password-submit').click();
await p.waitForTimeout(12000);
console.log('URL after login:', p.url());
const err = await p.getByTestId('kefi-login-password-error').textContent().catch(()=>null);
console.log('login error text:', err);
await b.close();
