// Generated by `manage.sh scaffold-service` — health/smoke spec for agora-api.
// Place at E2ETests/tests/agora/agora-api.spec.ts
// Starting point: probes + an auth-required check. Extend with real endpoints.
import { expect, test } from '@playwright/test';
import { AGORA_API_URL, tryRequest, waitForHealthy } from './agora-helpers.js';

test.describe('Agora Service Health Probes @agora-api @health', () => {
  const healthPaths = [
    { name: 'startup', path: '/health/start' },
    { name: 'liveness', path: '/health/live' },
    { name: 'readiness', path: '/health/ready' },
  ] as const;

  for (const probe of healthPaths) {
    test(`Service ${probe.name} probe should return healthy`, async ({ request }) => {
      const quickCheck = await tryRequest(request, probe.path);
      if (!quickCheck) {
        test.skip(true, `Service not available at ${AGORA_API_URL}`);
        return;
      }
      const { response, url } = await waitForHealthy(request, probe.path, 10_000);
      expect(response.status(), `Expected 200 OK from ${url}`).toBe(200);
    });
  }
});

test.describe('Agora Service API @agora-api', () => {
  test('a protected endpoint should require authentication', async ({ request }) => {
    // Replace the path with a real authenticated endpoint of the service.
    const result = await tryRequest(request, '/api/v1/agora', { method: 'GET' });
    if (!result) {
      test.skip(true, 'Service not available');
      return;
    }
    expect([401, 403]).toContain(result.response.status());
  });
});
