// E2E helpers for Agora (eShop) — merchant admin.
//
// Originally generated by `manage.sh scaffold-service`; extended by ES-04-close
// with the token/URL/CRUD helpers the real two-tier suite needs.
//
// The generic, product-agnostic building blocks (base-URL resolution, Keycloak-base derivation,
// transport-safe request, auth headers, health polling) now live in the shared
// @dloizides/e2e-helpers package. This file keeps only the AGORA-specific glue: the realm, the
// dual-audience ROPC token minted over a self-signed-cert-tolerant Playwright context, the JWT
// claim decoder, and the seeded merchant identities. Thin local wrappers re-supply the baked-in
// AGORA_API_URL so the spec call sites (`tryRequest(request, path, …)`, `waitForHealthy(request,
// path)`) are unchanged.
import { request as playwrightRequest } from '@playwright/test';
import type { APIRequestContext, APIResponse } from '@playwright/test';
import {
  bearer,
  jsonAuth,
  resolveBaseUrl,
  resolveKeycloakBaseUrl,
  tryRequest as sharedTryRequest,
  waitForHealthy as sharedWaitForHealthy,
  type TryRequestOptions,
} from '@dloizides/e2e-helpers';

// Re-export the shared auth-header helpers consumed unchanged by the agora specs.
export { bearer, jsonAuth };

/** Global route prefix of every AgoraService endpoint (MiddlewareConfig.cs). */
export const AGORA_API_PREFIX = '/api/v1';

export const AGORA_API_URL = resolveBaseUrl('AGORA_API_URL', 'http://localhost:5022');

/**
 * The merchant admin SPA (served same-origin by bff-agora). Returns null when
 * unset so the @ui tier can `test.skip` instead of failing — the dev PC cannot
 * always reach the WireGuard-only staging cluster. (Kept local: unlike
 * {@link resolveBaseUrl}, this deliberately has NO fallback default.)
 */
function resolveAgoraWebUrl(): string | null {
  const envUrl = process.env.AGORA_WEB_URL;
  if (envUrl && envUrl.trim()) {
    return envUrl.trim().replace(/\/+$/, '');
  }
  return null;
}

export const AGORA_WEB_URL = resolveAgoraWebUrl();

/** Realm that owns every merchant identity. */
export const AGORA_REALM = 'agora';

/** The two isolation-rig merchants, seeded by scripts/seed-realm-users.ps1. */
export const MERCHANT_A = 'agora-merchant-a';
export const MERCHANT_B = 'agora-merchant-b';

/**
 * Mint an access token for an `agora`-realm merchant via the BFF's confidential
 * client (ROPC / direct grant) — the same client and grant the deployed BFF uses,
 * so the token carries the same audiences (`agora-api` + `online-menu-api`) and,
 * critically, the `tenantId` claim that every tenant-scoped endpoint keys on.
 *
 * Returns null (never throws) when credentials or the KC URL are missing, so the
 * caller can `test.skip` with a useful reason while the unauthenticated negative
 * assertions still run.
 *
 * 🔴 Kept local rather than delegated to the shared `getRealmToken`, on purpose: it
 * mints the token over a Playwright request context with `ignoreHTTPSErrors: true`,
 * NOT global `fetch`. Staging Keycloak serves Traefik's DEFAULT SELF-SIGNED cert
 * (staging is WireGuard-only and has no Let's Encrypt cert — the deliberate standing
 * posture). Node's fetch rejects it with DEPTH_ZERO_SELF_SIGNED_CERT, which the shared
 * fetch-based helper would swallow into a `null` — i.e. every authed test would SKIP,
 * quietly, and the suite would report green while testing nothing. Playwright's request
 * context takes `ignoreHTTPSErrors` per-context, so the relaxation is scoped to this one
 * call instead of disabling TLS validation for the whole Node process
 * (NODE_TLS_REJECT_UNAUTHORIZED=0), which would also mask a genuinely bad cert on a PROD run.
 */
export async function getAgoraToken(
  username: string,
  password?: string,
): Promise<string | null> {
  const kcBase = resolveKeycloakBaseUrl();
  const pw = password ?? process.env.AGORA_TEST_PASSWORD?.trim();
  const clientId = process.env.AGORA_E2E_CLIENT_ID?.trim() || 'bff-agora-client';
  const clientSecret = process.env.AGORA_E2E_CLIENT_SECRET?.trim();

  if (!kcBase || !username || !pw) {
    return null;
  }

  const fields: Record<string, string> = {
    grant_type: 'password',
    client_id: clientId,
    username,
    password: pw,
    scope: 'openid',
  };
  if (clientSecret) {
    fields.client_secret = clientSecret;
  }

  const ctx = await playwrightRequest.newContext({ ignoreHTTPSErrors: true });
  try {
    const res = await ctx.post(
      `${kcBase}/realms/${AGORA_REALM}/protocol/openid-connect/token`,
      {
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        form: fields,
        timeout: 15_000,
      },
    );
    if (!res.ok()) {
      return null;
    }
    const body = (await res.json()) as { access_token?: string };
    return body.access_token ?? null;
  } catch {
    return null;
  } finally {
    await ctx.dispose();
  }
}

/** Decode a JWT payload claim without verifying the signature (test-only). */
export function tokenClaim(token: string, claim: string): unknown {
  const segment = token.split('.')[1];
  if (!segment) {
    return undefined;
  }
  const padded = segment.replace(/-/g, '+').replace(/_/g, '/');
  const json = Buffer.from(padded, 'base64').toString('utf8');
  return (JSON.parse(json) as Record<string, unknown>)[claim];
}

/**
 * Attempt a request against the agora-api; returns null when unreachable so specs
 * can `test.skip` gracefully in environments where the service isn't deployed. Thin
 * wrapper over the shared `tryRequest` that supplies the baked-in {@link AGORA_API_URL}.
 */
export function tryRequest(
  request: APIRequestContext,
  path: string,
  options: TryRequestOptions = {},
): Promise<{ response: APIResponse; url: string } | null> {
  return sharedTryRequest(request, AGORA_API_URL, path, options);
}

/**
 * Poll a health path until it returns 2xx, or until `timeoutMs` elapses. Wraps the shared
 * helper with the agora-api base. Contract preserved: NEVER throws on timeout — returns the
 * LAST response so the caller can assert on the real status code.
 */
export function waitForHealthy(
  request: APIRequestContext,
  path: string,
  timeoutMs = 30_000,
): Promise<{ response: APIResponse; url: string }> {
  return sharedWaitForHealthy(request, AGORA_API_URL, path, timeoutMs);
}
