// E2E helpers for Agora (eShop) — merchant admin.
//
// Originally generated by `manage.sh scaffold-service`; extended by ES-04-close
// with the token/URL/CRUD helpers the real two-tier suite needs.
import { expect, request as playwrightRequest } from '@playwright/test';
import type { APIRequestContext, APIResponse } from '@playwright/test';

/** Global route prefix of every AgoraService endpoint (MiddlewareConfig.cs). */
export const AGORA_API_PREFIX = '/api/v1';

function resolveAgoraApiUrl(): string {
  const envUrl = process.env.AGORA_API_URL;
  if (envUrl && envUrl.trim()) {
    return envUrl.trim().replace(/\/+$/, '');
  }
  return 'http://localhost:5022';
}

/**
 * The merchant admin SPA (served same-origin by bff-agora). Returns null when
 * unset so the @ui tier can `test.skip` instead of failing — the dev PC cannot
 * always reach the WireGuard-only staging cluster.
 */
function resolveAgoraWebUrl(): string | null {
  const envUrl = process.env.AGORA_WEB_URL;
  if (envUrl && envUrl.trim()) {
    return envUrl.trim().replace(/\/+$/, '');
  }
  return null;
}

export const AGORA_API_URL = resolveAgoraApiUrl();
export const AGORA_WEB_URL = resolveAgoraWebUrl();

/** Realm that owns every merchant identity. */
export const AGORA_REALM = 'agora';

/**
 * Derive the Keycloak base URL (no `/realms/...` suffix) from KEYCLOAK_URL or
 * KEYCLOAK_ISSUER. Mirrors helpers/realm-token-helper.ts. Returns null rather
 * than silently defaulting, so a spec can never accidentally mint a token
 * against the WRONG Keycloak (e.g. prod) just because an env var was missing.
 */
function resolveKeycloakBaseUrl(): string | null {
  const explicit = process.env.KEYCLOAK_URL?.trim();
  if (explicit) {
    return explicit.replace(/\/+$/, '');
  }
  const issuer = process.env.KEYCLOAK_ISSUER?.trim();
  if (!issuer) {
    return null;
  }
  const match = /^(.*?)\/realms\/[^/]+/.exec(issuer);
  return match?.[1] ? match[1].replace(/\/+$/, '') : null;
}

/** The two isolation-rig merchants, seeded by scripts/seed-realm-users.ps1. */
export const MERCHANT_A = 'agora-merchant-a';
export const MERCHANT_B = 'agora-merchant-b';

/**
 * Mint an access token for an `agora`-realm merchant via the BFF's confidential
 * client (ROPC / direct grant) — the same client and grant the deployed BFF uses,
 * so the token carries the same audiences (`agora-api` + `online-menu-api`) and,
 * critically, the `tenantId` claim that every tenant-scoped endpoint keys on.
 *
 * Returns null (never throws) when credentials or the KC URL are missing, so the
 * caller can `test.skip` with a useful reason while the unauthenticated negative
 * assertions still run.
 */
export async function getAgoraToken(
  username: string,
  password?: string,
): Promise<string | null> {
  const kcBase = resolveKeycloakBaseUrl();
  const pw = password ?? process.env.AGORA_TEST_PASSWORD?.trim();
  const clientId = process.env.AGORA_E2E_CLIENT_ID?.trim() || 'bff-agora-client';
  const clientSecret = process.env.AGORA_E2E_CLIENT_SECRET?.trim();

  if (!kcBase || !username || !pw) {
    return null;
  }

  const fields: Record<string, string> = {
    grant_type: 'password',
    client_id: clientId,
    username,
    password: pw,
    scope: 'openid',
  };
  if (clientSecret) {
    fields.client_secret = clientSecret;
  }

  // NOT global fetch. Staging Keycloak serves Traefik's DEFAULT SELF-SIGNED cert
  // (staging is WireGuard-only and has no Let's Encrypt cert — the deliberate
  // standing posture). Node's fetch rejects it with DEPTH_ZERO_SELF_SIGNED_CERT,
  // which this function would swallow into a `null` — i.e. every authed test would
  // SKIP, quietly, and the suite would report green while testing nothing.
  //
  // Playwright's request context takes `ignoreHTTPSErrors` per-context, so the
  // relaxation is scoped to this one call instead of disabling TLS validation for
  // the whole Node process (NODE_TLS_REJECT_UNAUTHORIZED=0), which would also mask
  // a genuinely bad cert on a PROD run.
  const ctx = await playwrightRequest.newContext({ ignoreHTTPSErrors: true });
  try {
    const res = await ctx.post(
      `${kcBase}/realms/${AGORA_REALM}/protocol/openid-connect/token`,
      {
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        form: fields,
        timeout: 15_000,
      },
    );
    if (!res.ok()) {
      return null;
    }
    const body = (await res.json()) as { access_token?: string };
    return body.access_token ?? null;
  } catch {
    return null;
  } finally {
    await ctx.dispose();
  }
}

/** Decode a JWT payload claim without verifying the signature (test-only). */
export function tokenClaim(token: string, claim: string): unknown {
  const segment = token.split('.')[1];
  if (!segment) {
    return undefined;
  }
  const padded = segment.replace(/-/g, '+').replace(/_/g, '/');
  const json = Buffer.from(padded, 'base64').toString('utf8');
  return (JSON.parse(json) as Record<string, unknown>)[claim];
}

export function bearer(token: string): Record<string, string> {
  return { Authorization: `Bearer ${token}` };
}

export function jsonAuth(token: string): Record<string, string> {
  return { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' };
}

/**
 * Attempt a request against the service; returns null when unreachable so specs
 * can `test.skip` gracefully in environments where the service isn't deployed.
 */
export async function tryRequest(
  request: APIRequestContext,
  path: string,
  options: {
    method?: 'GET' | 'POST' | 'DELETE' | 'PUT';
    data?: unknown;
    headers?: Record<string, string>;
  } = {},
): Promise<{ response: APIResponse; url: string } | null> {
  const url = `${AGORA_API_URL}${path}`;
  try {
    const response = await request.fetch(url, {
      method: options.method ?? 'GET',
      data: options.data as never,
      headers: options.headers,
      timeout: 10_000,
    });
    return { response, url };
  } catch {
    return null;
  }
}

/**
 * Poll a health path until it returns 2xx, or until `timeoutMs` elapses.
 *
 * Uses `expect.poll` rather than a hand-rolled `while (true)` + `setTimeout` loop:
 * the repo's `no-set-timeout-in-promise` ESLint rule bans the latter (a fixed sleep
 * is a flake factory — it is both slower than necessary when the service is already
 * up and too short when it is genuinely starting).
 *
 * Contract preserved: this NEVER throws on timeout. It returns the LAST response so
 * the caller can assert on the real status code and produce a useful failure message
 * (`expect(response.status()).toBe(200)`), instead of an opaque poll-timeout error.
 */
export async function waitForHealthy(
  request: APIRequestContext,
  path: string,
  timeoutMs = 30_000,
): Promise<{ response: APIResponse; url: string }> {
  const url = `${AGORA_API_URL}${path}`;
  let last: APIResponse | undefined;

  try {
    await expect
      .poll(
        async () => {
          last = await request.fetch(url, { timeout: 5_000 });
          return last.ok();
        },
        { timeout: timeoutMs, intervals: [250, 500, 1_000] },
      )
      .toBe(true);
  } catch {
    // Timed out — fall through and hand the caller the last response we saw.
  }

  if (!last) {
    last = await request.fetch(url, { timeout: 5_000 });
  }

  return { response: last, url };
}
