// Generated by `manage.sh scaffold-service` — E2E helpers for agora-api.
// Place at E2ETests/tests/agora/agora-helpers.ts
import { expect } from '@playwright/test';
import type { APIRequestContext, APIResponse } from '@playwright/test';

function resolveAgoraApiUrl(): string {
  const envUrl = process.env.AGORA_API_URL;
  if (envUrl && envUrl.trim()) {
    return envUrl.trim().replace(/\/+$/, '');
  }
  return 'http://localhost:5022';
}

export const AGORA_API_URL = resolveAgoraApiUrl();

/**
 * Attempt a request against the service; returns null when unreachable so specs
 * can `test.skip` gracefully in environments where the service isn't deployed.
 */
export async function tryRequest(
  request: APIRequestContext,
  path: string,
  options: {
    method?: 'GET' | 'POST' | 'DELETE' | 'PUT';
    data?: unknown;
    headers?: Record<string, string>;
  } = {},
): Promise<{ response: APIResponse; url: string } | null> {
  const url = `${AGORA_API_URL}${path}`;
  try {
    const response = await request.fetch(url, {
      method: options.method ?? 'GET',
      data: options.data as never,
      headers: options.headers,
      timeout: 10_000,
    });
    return { response, url };
  } catch {
    return null;
  }
}

/**
 * Poll a health path until it returns 2xx, or until `timeoutMs` elapses.
 *
 * Uses `expect.poll` rather than a hand-rolled `while (true)` + `setTimeout` loop:
 * the repo's `no-set-timeout-in-promise` ESLint rule bans the latter (a fixed sleep
 * is a flake factory — it is both slower than necessary when the service is already
 * up and too short when it is genuinely starting).
 *
 * Contract preserved: this NEVER throws on timeout. It returns the LAST response so
 * the caller can assert on the real status code and produce a useful failure message
 * (`expect(response.status()).toBe(200)`), instead of an opaque poll-timeout error.
 */
export async function waitForHealthy(
  request: APIRequestContext,
  path: string,
  timeoutMs = 30_000,
): Promise<{ response: APIResponse; url: string }> {
  const url = `${AGORA_API_URL}${path}`;
  let last: APIResponse | undefined;

  try {
    await expect
      .poll(
        async () => {
          last = await request.fetch(url, { timeout: 5_000 });
          return last.ok();
        },
        { timeout: timeoutMs, intervals: [250, 500, 1_000] },
      )
      .toBe(true);
  } catch {
    // Timed out — fall through and hand the caller the last response we saw.
  }

  if (!last) {
    last = await request.fetch(url, { timeout: 5_000 });
  }

  return { response: last, url };
}
