/**
 * KUCY-shaped landing-config fixture (decision #13 of the plan doc).
 *
 * Builds a `SavedLandingDto` with `template='kucy'` and a `LandingConfigDto`
 * mirroring KUCY's shape (every section KUCY's KucyLandingConfig.Build()
 * populates), but with canary-prefixed content + placeholder images +
 * counts scaled down (2/2/1/2/2 across teachers/ambassadors/media/slots/rooms).
 *
 * Why a TS fixture instead of fetching KUCY's saved config: the spec must be
 * deterministic and self-contained. The canary tenant has no live KUCY
 * config to read; we ship the shape with the spec.
 *
 * Why canary-prefix every string: trivially identifiable as test data + safe
 * for the canary sweep prefix-matching.
 *
 * DTO interfaces live in kefiKucyShapedConfig.types.ts (re-exported below) to
 * keep this file below the 300-line lint threshold.
 */

import {
  placeholderHero,
  placeholderLogo,
  placeholderPerson,
} from './kefiPlaceholderImages.js';
import type {
  LandingBranding,
  LandingCallToAction,
  LandingEventDetails,
  LandingParty,
  LandingPerformerGroup,
  LandingSchedule,
  LandingSection,
  LandingSocialLink,
  LandingVenue,
  SavedLandingDto,
} from './kefiKucyShapedConfig.types.js';

export type { SavedLandingDto } from './kefiKucyShapedConfig.types.js';

/**
 * Build a KUCY-shaped SavedLandingDto carrying canary-prefixed content. Mirror
 * of KefiService/Kefi/src/Kefi.LedgerImporter/KucyLandingConfig.cs — every
 * section that the C# builder populates is populated here.
 *
 * `canaryPrefix` is the slug-shaped prefix (`e2c-{id}-`) — every text field
 * the canary "owns" carries it so the canary sweep recognises the data.
 */
export function buildKucyShapedConfig(canaryPrefix: string): SavedLandingDto {
  return {
    template: 'kucy',
    config: {
      branding: buildBranding(canaryPrefix),
      eventDetails: buildEventDetails(canaryPrefix),
      venue: buildVenue(canaryPrefix),
      register: buildRegister(canaryPrefix),
      sections: buildSections(canaryPrefix),
      performerGroups: buildPerformerGroups(canaryPrefix),
      schedule: buildSchedule(canaryPrefix),
      party: buildParty(canaryPrefix),
      socialLinks: buildSocialLinks(canaryPrefix),
    },
  };
}

function buildBranding(prefix: string): LandingBranding {
  return {
    name: `${prefix}Canary Brand`,
    tagline: 'Synthetic E2E canary — auto-sweeps',
    edition: 'Canary Edition · auto-deleted',
    heroImageUrl: placeholderHero(),
    logoUrl: placeholderLogo(),
    primaryColor: '#3a81a8',
    accentColor: '#c96a3d',
    backgroundColors: [
      '#2f79a3', '#3a81a8', '#6ba3c2', '#a7c4d2',
      '#dbc396', '#e8a070', '#c96a3d', '#a84a22',
    ],
  };
}

function buildEventDetails(prefix: string): LandingEventDetails {
  return {
    dateLabel: 'Synthetic Event Date',
    classesTime: '16:00 – 20:25',
    partyTime: '21:30 – Late',
    locationLabel: 'Synthetic, CY',
    eyebrow: 'Synthetic Purpose',
    heading: `${prefix}Canary Heading`,
    description:
      `${prefix}Synthetic landing page generated by the nightly Kefi tenant-lifecycle ` +
      `E2E spec. Every record carrying this prefix is auto-swept within seconds.`,
    stats: [
      { value: '2', label: `${prefix}Workshops` },
      { value: '2', label: `${prefix}Local Teachers` },
      { value: '2', label: `${prefix}Rooms` },
      { value: '1', label: `${prefix}Island` },
    ],
  };
}

function buildVenue(prefix: string): LandingVenue {
  return {
    name: `${prefix}Synthetic Test Venue`,
    city: 'Synthetic City · Cyprus',
    address: 'Synthetic Address 1, 9999 SyntheticVille',
    mapUrl: 'https://www.google.com/maps/dir/?api=1&destination=Synthetic+Test+Venue',
  };
}

function buildRegister(prefix: string): LandingCallToAction {
  return {
    label: 'Get a Pass',
    url: '#register',
    note: `${prefix}Synthetic pay-at-door note — not a real registration channel.`,
  };
}

function buildSections(prefix: string): LandingSection[] {
  return [
    {
      key: 'media',
      eyebrow: 'Synthetic Capture',
      title: 'Photo & Video',
      body:
        `${prefix}Synthetic section body — covers the same template-1 ` +
        `code path KUCY's media section exercises in production.`,
    },
    {
      key: 'past',
      eyebrow: 'Archive',
      title: 'Past Editions',
      body:
        `${prefix}Synthetic archive section. Used by the canary nightly to ` +
        `verify the template's section repeater renders.`,
    },
  ];
}

function buildPerformerGroups(prefix: string): LandingPerformerGroup[] {
  return [
    {
      key: 'teachers',
      eyebrow: 'The Line-Up',
      title: 'Teachers',
      subtitle: 'Two synthetic teachers — enough to exercise the grid + parallel-class slot.',
      performers: [
        {
          id: 'canary-teacher-1',
          name: `${prefix}Teacher One`,
          topic: 'Synthetic Topic A',
          room: 'Room Fuego',
          level: 'Open Level',
          photoUrl: placeholderPerson(),
          instagramHandle: '@canary_teacher_1',
          instagramUrl: 'https://www.instagram.com/canary_teacher_1/',
        },
        {
          id: 'canary-teacher-2',
          name: `${prefix}Teacher Two`,
          topic: 'Synthetic Topic B',
          room: 'Room Garden',
          level: 'Inter / Adv',
          photoUrl: placeholderPerson(),
          instagramHandle: '@canary_teacher_2',
          instagramUrl: 'https://www.instagram.com/canary_teacher_2/',
        },
      ],
    },
    {
      key: 'ambassadors',
      eyebrow: 'Community',
      title: 'Ambassadors',
      subtitle: 'Two synthetic ambassadors — exercises the second performer-group block.',
      performers: [
        {
          id: 'canary-ambassador-1',
          name: `${prefix}Ambassador One`,
          photoUrl: placeholderPerson(),
          instagramHandle: '@canary_amb_1',
          instagramUrl: 'https://www.instagram.com/canary_amb_1/',
        },
        {
          id: 'canary-ambassador-2',
          name: `${prefix}Ambassador Two`,
          photoUrl: placeholderPerson(),
          instagramHandle: '@canary_amb_2',
          instagramUrl: 'https://www.instagram.com/canary_amb_2/',
        },
      ],
    },
    {
      key: 'media',
      eyebrow: 'Capture',
      title: 'Photo & Video Crew',
      subtitle: 'One synthetic media person.',
      performers: [
        {
          id: 'canary-media-1',
          name: `${prefix}Media Person`,
          role: 'Photographer',
          photoUrl: placeholderPerson(),
          instagramHandle: '@canary_media_1',
          instagramUrl: 'https://www.instagram.com/canary_media_1/',
        },
      ],
    },
  ];
}

function buildSchedule(prefix: string): LandingSchedule {
  return {
    eyebrow: 'Schedule',
    title: 'Classes',
    subtitle: `${prefix}Two slots — second slot runs parallel classes to exercise the multi-class branch.`,
    slots: [
      {
        id: 'canary-slot-1',
        time: '16:00 – 16:55',
        classes: [
          {
            teacher: `${prefix}Teacher One`,
            topic: 'Synthetic Topic A',
            room: 'Room Fuego',
            level: 'Open Level',
          },
        ],
      },
      {
        id: 'canary-slot-2',
        time: '17:10 – 18:05',
        classes: [
          {
            teacher: `${prefix}Teacher One`,
            topic: 'Synthetic Topic A (Part 2)',
            room: 'Room Fuego',
            level: 'Open Level',
          },
          {
            teacher: `${prefix}Teacher Two`,
            topic: 'Synthetic Topic B',
            room: 'Room Garden',
            level: 'Inter / Adv',
          },
        ],
      },
    ],
  };
}

function buildParty(prefix: string): LandingParty {
  return {
    eyebrow: 'After Dark',
    title: 'The Party',
    subtitle: `${prefix}Two rooms — exercises the room repeater.`,
    rooms: [
      {
        id: 'canary-room-fuego',
        name: 'Room Fuego',
        music: 'Synthetic Salsa & Bachata',
        dj: 'DJ Canary',
      },
      {
        id: 'canary-room-garden',
        name: 'Room Garden',
        music: 'Synthetic Urban Kiz & Kizomba',
        dj: 'DJ Synthesizer',
      },
    ],
  };
}

function buildSocialLinks(prefix: string): LandingSocialLink[] {
  return [
    {
      id: 'instagram',
      kind: 'instagram',
      label: `${prefix}Canary on Instagram`,
      url: 'https://www.instagram.com/canary_kefi_e2e/',
    },
    {
      id: 'facebook',
      kind: 'facebook',
      label: `${prefix}Canary on Facebook`,
      url: 'https://www.facebook.com/canary_kefi_e2e/',
    },
  ];
}
