// Originally generated by `manage.sh scaffold-service` — E2E helpers for ichnos-api.
// Place at E2ETests/tests/ichnos/ichnos-helpers.ts
//
// The generic, product-agnostic building blocks (transport-safe request, ROPC realm token, auth
// headers, health polling, CSV multipart, username/email derivation) now live in the shared
// @dloizides/e2e-helpers package. This file keeps only the ichnos-specific glue: the API/web base
// URLs, the BFF anti-forgery contract, onboarding/register/login over the BFF, API-key issuance, and
// the crypto-address fixtures. Thin local wrappers re-supply the baked-in ICHNOS_API_URL so the spec
// call sites (`tryRequest(request, path, ...)`, `waitForHealthy(request, path)`) are unchanged.
import type { APIRequestContext, APIResponse } from '@playwright/test';
import {
  bearer,
  csvMultipart,
  deriveUsername,
  getRealmToken,
  jsonAuth,
  resolveBaseUrl,
  tryRequest as sharedTryRequest,
  uniqueEmail,
  waitForHealthy as sharedWaitForHealthy,
  type TryRequestOptions,
} from '@dloizides/e2e-helpers';

// Re-export the shared helpers consumed unchanged by the ichnos specs.
export { bearer, csvMultipart, deriveUsername, jsonAuth };

export const ICHNOS_API_URL = resolveBaseUrl('ICHNOS_API_URL', 'http://localhost:5099');

/**
 * Attempt a request against the ichnos-api; returns null when unreachable so specs can `test.skip`
 * gracefully in environments where the service isn't deployed. Thin wrapper over the shared
 * `tryRequest` that supplies the baked-in {@link ICHNOS_API_URL} base.
 */
export function tryRequest(
  request: APIRequestContext,
  path: string,
  options: TryRequestOptions = {},
): Promise<{ response: APIResponse; url: string } | null> {
  return sharedTryRequest(request, ICHNOS_API_URL, path, options);
}

/**
 * Acquire an `ichnos`-realm access token via Resource Owner Password Credentials. Returns null (so the
 * caller `test.skip`s the authed assertions) when the Keycloak base / credentials aren't configured —
 * the unauthenticated negative assertions in the spec always run regardless.
 *
 * MUST use a TENANT user (carries a `tenantId` claim), not the platform superUser — screenings are
 * tenant-scoped and reject a tenant-less principal with 401. Credentials come from
 * ICHNOS_TEST_USERNAME / ICHNOS_TEST_PASSWORD (the seeded `ichnos-tenant` user).
 *
 * Client is configurable: defaults to `bff-ichnos-client` (the confidential client whose
 * direct-access-grant path M0 proved end-to-end); the runner supplies its secret via
 * ICHNOS_E2E_CLIENT_SECRET. A public client with DAG can be used by setting ICHNOS_E2E_CLIENT_ID with
 * no secret.
 */
export function getIchnosToken(): Promise<string | null> {
  return getRealmToken('ichnos', {
    username: process.env.ICHNOS_TEST_USERNAME?.trim() ?? '',
    password: process.env.ICHNOS_TEST_PASSWORD?.trim() ?? '',
    clientId: process.env.ICHNOS_E2E_CLIENT_ID?.trim() || 'bff-ichnos-client',
    clientSecret: process.env.ICHNOS_E2E_CLIENT_SECRET?.trim(),
  });
}

/** Poll a health path until 200 or timeout. Wraps the shared helper with the ichnos-api base. */
export function waitForHealthy(
  request: APIRequestContext,
  path: string,
  timeoutMs = 30_000,
): Promise<{ response: APIResponse; url: string }> {
  return sharedWaitForHealthy(request, ICHNOS_API_URL, path, timeoutMs);
}

// ---------------------------------------------------------------------------
// M1-10 two-tier E2E — BFF onboarding (F1), API keys (F3), batch (F4), billing (F7).
// ---------------------------------------------------------------------------

/**
 * The ichnos-web SPA host — same origin as the `bff-ichnos` BFF. `/bff/*` auth endpoints and the
 * `/bff/api/*` proxy both live here. Resolved from ICHNOS_WEB_URL (staging:
 * https://staging.app.ichnos.dloizides.com); when unset the onboarding + portal specs `test.skip`
 * gracefully (dev PC can't reach it).
 */
export function resolveIchnosWebUrl(): string | null {
  const envUrl = process.env.ICHNOS_WEB_URL;
  if (envUrl && envUrl.trim()) return envUrl.trim().replace(/\/+$/, '');
  return null;
}

export const ICHNOS_WEB_URL = resolveIchnosWebUrl();

/** The BFF's anti-forgery contract — every state-changing `/bff/*` call needs this header + an allow-listed Origin. */
export const BFF_CSRF_HEADER = 'X-BFF-Csrf';
export const BFF_CSRF_VALUE = '1';

/** A well-formed, plainly non-sanctioned address — screens as "clear". */
export const CLEAR_BTC_ADDRESS = { chain: 'BTC', address: '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa' };

/** A REAL OFAC-listed TRON address — screens as a DIRECT "direct" hit against OFAC. */
export const SANCTIONED_TRX_ADDRESS = { chain: 'TRX', address: 'TNiq9AXBp9EjUqhDhrwrfvAA8U3GUQZH81' };

/** Shared strong password for the E2E-registered onboarding user. */
export const ICHNOS_E2E_PASSWORD = 'Str0ng!ichnosE2e1';

/**
 * POST a `/bff/*` endpoint with the CSRF header + explicit Origin the BFF requires (Playwright's
 * request context — unlike a browser — does not add Origin). Returns null on a transport error so the
 * caller can `test.skip`. Cookies set by the BFF (the session cookie) persist on the caller's request
 * context, so a register → login → proxied-screen chain shares one session.
 */
export async function bffTryPost(
  request: APIRequestContext,
  webUrl: string,
  path: string,
  data: unknown,
): Promise<APIResponse | null> {
  try {
    return await request.post(`${webUrl}${path}`, {
      headers: { [BFF_CSRF_HEADER]: BFF_CSRF_VALUE, Origin: webUrl, 'Content-Type': 'application/json' },
      data: data as never,
      timeout: 20_000,
    });
  } catch {
    return null;
  }
}

/** A unique email per run (timestamp + random) so each register creates a fresh tenant. */
export function uniqueIchnosEmail(): string {
  return uniqueEmail('ichnos-e2e');
}

/** A freshly-registered onboarding user + the raw register response. */
export interface RegisteredIchnosUser {
  email: string;
  username: string;
  password: string;
  response: APIResponse;
}

/**
 * Register a FRESH ichnos user via the BFF (`POST /bff/register`). Username is DERIVED from the email
 * (raw email 400s); a unique email per run means a fresh tenant each time. Returns null when the BFF is
 * unreachable.
 */
export async function registerIchnosUser(
  request: APIRequestContext,
  webUrl: string,
): Promise<RegisteredIchnosUser | null> {
  const email = uniqueIchnosEmail();
  const username = deriveUsername(email);
  const response = await bffTryPost(request, webUrl, '/bff/register', {
    firstName: 'Ichnos',
    lastName: 'E2E',
    username,
    email,
    password: ICHNOS_E2E_PASSWORD,
    tenantName: `Ichnos E2E ${username}`,
    verifyUrlTemplate: `${webUrl}/verify-email?token={token}`,
  });
  if (!response) return null;
  return { email, username, password: ICHNOS_E2E_PASSWORD, response };
}

/**
 * Log in via the BFF (`POST /bff/login`). The BFF field is `username`, set to the EMAIL — Keycloak
 * resolves email → user (register needs an @-free username; login does not). Mirrors the shipped
 * bffAuthClient.login call.
 */
export function bffLogin(
  request: APIRequestContext,
  webUrl: string,
  email: string,
  password: string,
): Promise<APIResponse | null> {
  return bffTryPost(request, webUrl, '/bff/login', { username: email, password });
}

/** The plaintext-once result of issuing a customer API key. */
export interface IssueApiKeyResult {
  id: string;
  plaintext: string;
  prefix: string;
  label: string;
  createdAt: string;
}

/**
 * Issue a customer API key (JWT-authed `POST /v1/api-keys`). Returns the parsed result (plaintext
 * returned ONCE) on a 2xx, else null.
 */
export async function issueApiKey(
  request: APIRequestContext,
  token: string,
  label = 'e2e',
): Promise<IssueApiKeyResult | null> {
  const result = await tryRequest(request, '/v1/api-keys', {
    method: 'POST',
    data: { label },
    headers: jsonAuth(token),
  });
  if (!result || result.response.status() >= 300) return null;
  return (await result.response.json()) as IssueApiKeyResult;
}

// --- M3 Wave-4 — monitoring / alerts / webhooks / regulator packs shared bits ---
/** HTTP 402 — the Growth+ plan gate response emitted by PlanGate.WritePaymentRequiredAsync. */
export const PAYMENT_REQUIRED = 402;

/** A PUBLIC https webhook sink the nightly runner can reach (both-channels delivery E2E); unset → skip. */
export const ICHNOS_WEBHOOK_SINK_URL: string | null = (() => {
  const envUrl = process.env.ICHNOS_WEBHOOK_SINK_URL;
  return envUrl && envUrl.trim() ? envUrl.trim().replace(/\/+$/, '') : null;
})();

/** Whether an IMAP inbox is configured to assert a real alert EMAIL (host+user+password). */
export function hasEmailInboxConfigured(): boolean {
  const host = process.env.ICHNOS_IMAP_HOST?.trim() || process.env.IMAP_HOST?.trim();
  const user = process.env.ICHNOS_IMAP_USER?.trim() || process.env.IMAP_USER?.trim();
  const pass = process.env.ICHNOS_IMAP_PASSWORD?.trim() || process.env.IMAP_PASSWORD?.trim();
  return Boolean(host && user && pass);
}
