// Generated by `manage.sh scaffold-service` — E2E helpers for ichnos-api.
// Place at E2ETests/tests/ichnos/ichnos-helpers.ts
import type { APIRequestContext, APIResponse } from '@playwright/test';

function resolveIchnosApiUrl(): string {
  const envUrl = process.env.ICHNOS_API_URL;
  if (envUrl && envUrl.trim()) {
    return envUrl.trim().replace(/\/+$/, '');
  }
  return 'http://localhost:5099';
}

export const ICHNOS_API_URL = resolveIchnosApiUrl();

/**
 * Attempt a request against the service; returns null when unreachable so specs
 * can `test.skip` gracefully in environments where the service isn't deployed.
 */
export async function tryRequest(
  request: APIRequestContext,
  path: string,
  options: {
    method?: 'GET' | 'POST' | 'DELETE' | 'PUT';
    data?: unknown;
    headers?: Record<string, string>;
  } = {},
): Promise<{ response: APIResponse; url: string } | null> {
  const url = `${ICHNOS_API_URL}${path}`;
  try {
    const response = await request.fetch(url, {
      method: options.method ?? 'GET',
      data: options.data as never,
      headers: options.headers,
      timeout: 10_000,
    });
    return { response, url };
  } catch {
    return null;
  }
}

/** Poll a health path until 200 or timeout. */
export async function waitForHealthy(
  request: APIRequestContext,
  path: string,
  timeoutMs = 30_000,
): Promise<{ response: APIResponse; url: string }> {
  const url = `${ICHNOS_API_URL}${path}`;
  const deadline = Date.now() + timeoutMs;
  let last: APIResponse | undefined;
  // eslint-disable-next-line no-constant-condition
  while (true) {
    last = await request.fetch(url, { timeout: 5_000 });
    if (last.ok()) return { response: last, url };
    if (Date.now() > deadline) return { response: last, url };
    await new Promise((r) => setTimeout(r, 1_000));
  }
}
