// Generated by `manage.sh scaffold-service` — E2E helpers for ichnos-api.
// Place at E2ETests/tests/ichnos/ichnos-helpers.ts
import type { APIRequestContext, APIResponse } from '@playwright/test';
import { setTimeout as delay } from 'timers/promises';

function resolveIchnosApiUrl(): string {
  const envUrl = process.env.ICHNOS_API_URL;
  if (envUrl && envUrl.trim()) {
    return envUrl.trim().replace(/\/+$/, '');
  }
  return 'http://localhost:5099';
}

export const ICHNOS_API_URL = resolveIchnosApiUrl();

/**
 * Attempt a request against the service; returns null when unreachable so specs
 * can `test.skip` gracefully in environments where the service isn't deployed.
 */
export async function tryRequest(
  request: APIRequestContext,
  path: string,
  options: {
    method?: 'GET' | 'POST' | 'DELETE' | 'PUT';
    data?: unknown;
    headers?: Record<string, string>;
  } = {},
): Promise<{ response: APIResponse; url: string } | null> {
  const url = `${ICHNOS_API_URL}${path}`;
  try {
    const response = await request.fetch(url, {
      method: options.method ?? 'GET',
      data: options.data as never,
      headers: options.headers,
      timeout: 10_000,
    });
    return { response, url };
  } catch {
    return null;
  }
}

/**
 * Acquire an `ichnos`-realm access token via Resource Owner Password Credentials.
 *
 * Returns null (so the caller `test.skip`s the authed assertions) when the
 * Keycloak base / credentials / client aren't configured in the active env —
 * the unauthenticated negative assertions in the spec always run regardless.
 *
 * MUST use a TENANT user (carries a `tenantId` claim), not the platform
 * superUser — screenings are tenant-scoped and reject a tenant-less principal
 * with 401. Credentials come from ICHNOS_TEST_USERNAME / ICHNOS_TEST_PASSWORD
 * (the seeded `ichnos-tenant` user); if unset the authed test skips rather than
 * false-fail on superUser.
 *
 * Client is configurable: defaults to `bff-ichnos-client` (the confidential
 * client whose direct-access-grant path M0 proved end-to-end); the runner
 * supplies its secret via ICHNOS_E2E_CLIENT_SECRET. A public client with DAG
 * can be used by setting ICHNOS_E2E_CLIENT_ID with no secret.
 */
export async function getIchnosToken(): Promise<string | null> {
  const kcBase = resolveKeycloakBaseUrl();
  const username = process.env.ICHNOS_TEST_USERNAME?.trim();
  const password = process.env.ICHNOS_TEST_PASSWORD?.trim();
  if (!kcBase || !username || !password) return null;

  const clientId = process.env.ICHNOS_E2E_CLIENT_ID?.trim() || 'bff-ichnos-client';
  const clientSecret = process.env.ICHNOS_E2E_CLIENT_SECRET?.trim();

  const fields: Record<string, string> = {
    grant_type: 'password',
    client_id: clientId,
    username,
    password,
    scope: 'openid',
  };
  if (clientSecret) fields.client_secret = clientSecret;

  try {
    const res = await fetch(`${kcBase}/realms/ichnos/protocol/openid-connect/token`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams(fields).toString(),
    });
    if (!res.ok) return null;
    const body = (await res.json()) as { access_token?: string };
    return body.access_token ?? null;
  } catch {
    return null;
  }
}

/** Derive the Keycloak base URL (no `/realms/...`) from KEYCLOAK_URL or KEYCLOAK_ISSUER. */
function resolveKeycloakBaseUrl(): string | null {
  const explicit = process.env.KEYCLOAK_URL?.trim();
  if (explicit) return explicit.replace(/\/+$/, '');
  const issuer = process.env.KEYCLOAK_ISSUER?.trim();
  if (!issuer) return null;
  const match = /^(.*?)\/realms\/[^/]+/.exec(issuer);
  return match?.[1] ? match[1].replace(/\/+$/, '') : null;
}

/** Poll a health path until 200 or timeout. */
export async function waitForHealthy(
  request: APIRequestContext,
  path: string,
  timeoutMs = 30_000,
): Promise<{ response: APIResponse; url: string }> {
  const url = `${ICHNOS_API_URL}${path}`;
  const deadline = Date.now() + timeoutMs;
  let last: APIResponse = await request.fetch(url, { timeout: 5_000 });
  while (!last.ok() && Date.now() <= deadline) {
    await delay(1_000);
    last = await request.fetch(url, { timeout: 5_000 });
  }
  return { response: last, url };
}
